<?php

return [
    'countries' => [
        'AE' => array('old_domain'=>'ae.ogame.org','domain'=>'ae.ogame.gameforge.com','login'=>'ae.ogame.gameforge.com','lang'=>'ae','flag'=>'ae','slug'=>'arab-emirates'),
        'AR' => array('old_domain'=>'ogame.com.ar','domain'=>'ar.ogame.gameforge.com','login'=>'ar.ogame.gameforge.com','lang'=>'ar','flag'=>'ar','slug'=>'argentina'),
        'BA' => array('old_domain'=>'ogame.ba','domain'=>'ba.ogame.gameforge.com','login'=>'ba.ogame.gameforge.com','lang'=>'ba','flag'=>'ba','slug'=>'bosnia-and-herzegovina'),
        'BR' => array('old_domain'=>'ogame.com.br','domain'=>'br.ogame.gameforge.com','login'=>'br.ogame.gameforge.com','lang'=>'br','flag'=>'br','slug'=>'brazil'),
        'DE' => array('old_domain'=>'ogame.de','domain'=>'de.ogame.gameforge.com','login'=>'de.ogame.gameforge.com','lang'=>'de','flag'=>'de','slug'=>'germany'),
        'DK' => array('old_domain'=>'ogame.dk','domain'=>'dk.ogame.gameforge.com','login'=>'dk.ogame.gameforge.com','lang'=>'dk','flag'=>'dk','slug'=>'denmark'),
        'US' => array('old_domain'=>'ogame.us','domain'=>'us.ogame.gameforge.com','login'=>'us.ogame.gameforge.com','lang'=>'us','flag'=>'us','slug'=>'united-states'),
        'ES' => array('old_domain'=>'ogame.com.es','domain'=>'es.ogame.gameforge.com','login'=>'es.ogame.gameforge.com','lang'=>'es','flag'=>'es','slug'=>'spain'),
        'FR' => array('old_domain'=>'ogame.fr','domain'=>'fr.ogame.gameforge.com','login'=>'fr.ogame.gameforge.com','lang'=>'fr','flag'=>'fr','slug'=>'france'),
        'EN' => array('old_domain'=>'ogame.org','domain'=>'en.ogame.gameforge.com','login'=>'en.ogame.gameforge.com','lang'=>'en','flag'=>'gb','slug'=>'england'),
        'IT' => array('old_domain'=>'ogame.it','domain'=>'it.ogame.gameforge.com','login'=>'it.ogame.gameforge.com','lang'=>'it','flag'=>'it','slug'=>'italy'),
        'TR' => array('old_domain'=>'tr.ogame.org','domain'=>'tr.ogame.gameforge.com','login'=>'tr.ogame.gameforge.com','lang'=>'tr','flag'=>'tr','slug'=>'turkey'),
        'PL' => array('old_domain'=>'ogame.pl','domain'=>'pl.ogame.gameforge.com','login'=>'pl.ogame.gameforge.com','lang'=>'pl','flag'=>'pl','slug'=>'poland'),
        'GR' => array('old_domain'=>'ogame.gr','domain'=>'gr.ogame.gameforge.com','login'=>'gr.ogame.gameforge.com','lang'=>'gr','flag'=>'gr','slug'=>'greece'),
        'TW' => array('old_domain'=>'ogame.tw','domain'=>'tw.ogame.gameforge.com','login'=>'tw.ogame.gameforge.com','lang'=>'tw','flag'=>'tw','slug'=>'taiwan'),
        'JP' => array('old_domain'=>'ogame.jp','domain'=>'jp.ogame.gameforge.com','login'=>'jp.ogame.gameforge.com','lang'=>'jp','flag'=>'jp','slug'=>'japan'),
        'RU' => array('old_domain'=>'ogame.ru','domain'=>'ru.ogame.gameforge.com','login'=>'ru.ogame.gameforge.com','lang'=>'ru','flag'=>'ru','slug'=>'russia'),
        'MX' => array('old_domain'=>'mx.ogame.org','domain'=>'mx.ogame.gameforge.com','login'=>'mx.ogame.gameforge.com','lang'=>'mx','flag'=>'mx','slug'=>'mexico'),
        'PT' => array('old_domain'=>'ogame.pt','domain'=>'pt.ogame.gameforge.com','login'=>'pt.ogame.gameforge.com','lang'=>'pt','flag'=>'pt','slug'=>'portugal'),
        'NL' => array('old_domain'=>'ogame.nl','domain'=>'nl.ogame.gameforge.com','login'=>'nl.ogame.gameforge.com','lang'=>'nl','flag'=>'nl','slug'=>'netherlands'),
        'HR' => array('old_domain'=>'hr.ogame.org','domain'=>'hr.ogame.gameforge.com','login'=>'hr.ogame.gameforge.com','lang'=>'hr','flag'=>'hr','slug'=>'croatia'),
        'NO' => array('old_domain'=>'ogame.no','domain'=>'no.ogame.gameforge.com','login'=>'no.ogame.gameforge.com','lang'=>'no','flag'=>'no','slug'=>'norway'),
        'FI' => array('old_domain'=>'fi.ogame.org','domain'=>'fi.ogame.gameforge.com','login'=>'fi.ogame.gameforge.com','lang'=>'fi','flag'=>'fi','slug'=>'finland'),
        'SK' => array('old_domain'=>'ogame.sk','domain'=>'sk.ogame.gameforge.com','login'=>'sk.ogame.gameforge.com','lang'=>'sk','flag'=>'sk','slug'=>'slovakia'),
        'SE' => array('old_domain'=>'ogame.se','domain'=>'se.ogame.gameforge.com','login'=>'se.ogame.gameforge.com','lang'=>'se','flag'=>'se','slug'=>'sweden'),
        'SI' => array('old_domain'=>'ogame.si','domain'=>'si.ogame.gameforge.com','login'=>'si.ogame.gameforge.com','lang'=>'si','flag'=>'si','slug'=>'slovenia'),
        'CZ' => array('old_domain'=>'ogame.cz','domain'=>'cz.ogame.gameforge.com','login'=>'cz.ogame.gameforge.com','lang'=>'cz','flag'=>'cz','slug'=>'czech-republic'),
        'HU' => array('old_domain'=>'ogame.hu','domain'=>'hu.ogame.gameforge.com','login'=>'hu.ogame.gameforge.com','lang'=>'hu','flag'=>'hu','slug'=>'hungary'),
        'RO' => array('old_domain'=>'ogame.ro','domain'=>'ro.ogame.gameforge.com','login'=>'ro.ogame.gameforge.com','lang'=>'ro','flag'=>'ro','slug'=>'romania'),
        'PIONEERS' => array('old_domain'=>'pioneers.ogame.org','domain'=>'en.ogame.gameforge.com','login'=>'pioneers.ogame.gameforge.com','lang'=>'pioneers','flag'=>'england','slug'=>'pioneers-servers'),
    ],
    //Servers might be named differently
    'servers_by_name' => [
        'Andromeda'=>array('code'=>101,'weight'=>1),
        'Barym'=>array('code'=>102,'weight'=>1),
        'Capella'=>array('code'=>103,'weight'=>1),
        'Draco'=>array('code'=>104,'weight'=>1),
        'Electra'=>array('code'=>105,'weight'=>1),
        'Fornax'=>array('code'=>106,'weight'=>1),
        'Gemini'=>array('code'=>107,'weight'=>1),
        'Hydra'=>array('code'=>108,'weight'=>1),
        'Io'=>array('code'=>109,'weight'=>1),
        'Jupiter'=>array('code'=>110,'weight'=>1),
        'Kassiopeia'=>array('code'=>111,'weight'=>1),
        'Leo'=>array('code'=>112,'weight'=>1),
        'Mizar'=>array('code'=>113,'weight'=>1),
        'Nekkar'=>array('code'=>114,'weight'=>1),
        'Orion'=>array('code'=>115,'weight'=>1),
        'Pegasus'=>array('code'=>116,'weight'=>1),
        'Quantum'=>array('code'=>117,'weight'=>1),
        'Rigel'=>array('code'=>118,'weight'=>1),
        'Sirius'=>array('code'=>119,'weight'=>1),
        'Taurus'=>array('code'=>120,'weight'=>1),
        'Ursa'=>array('code'=>121,'weight'=>1),
        'Vega'=>array('code'=>122,'weight'=>1),
        'Wasat'=>array('code'=>123,'weight'=>1),
        'Xalynth'=>array('code'=>124,'weight'=>1),
        'Yakini'=>array('code'=>125,'weight'=>1),
        'Zagadra'=>array('code'=>126,'weight'=>1),

        'Antares'=>array('code'=>127,'weight'=>2),
        'Betelgeuse'=>array('code'=>128,'weight'=>2),
        'Cygnus'=>array('code'=>129,'weight'=>2),
        'Deimos'=>array('code'=>130,'weight'=>2),
        'Eridanus'=>array('code'=>131,'weight'=>2),

        'Fidis' => array('code'=>132, 'weight'=>2), //Code = 132, except for France
        'Ganimed' => array('code'=>133, 'weight'=>2),
        'Hyperion' => array('code'=>134, 'weight'=>2),
        'Izar' => array('code'=>135, 'weight'=>2),
        'Japetus' => array('code'=>136,'weight'=>2),
        'Kallisto' => array('code'=>137,'weight'=>2),
        'Libra' => array('code'=>138,'weight'=>2),
        'Melkur' => array('code'=>139,'weight'=>2),
        'Nusakan' => array('code'=>140,'weight'=>2),
        'Oberon' => array('code'=>141,'weight'=>2),
        'Polaris' => array('code'=>142,'weight'=>2),
        'Quaoar' => array('code'=>143,'weight'=>2),
        'Rhea' => array('code'=>144,'weight'=>2),
        'Spica' => array('code'=>145,'weight'=>2),
        'Tarazed' => array('code'=>146,'weight'=>2),
        'Uriel' => array('code'=>147,'weight'=>2),
        'V' => array('code'=>148,'weight'=>2),
        'W' => array('code'=>149,'weight'=>2),
        'X' => array('code'=>150,'weight'=>2),
        'Y' => array('code'=>151,'weight'=>2),
        'Z' => array('code'=>152,'weight'=>2),

        'Halloween' => array('code'=>202,'weight'=>0) //Apparently, Ogame won't last for too long
    ],
    'private_servers' => [691,692,803,802],
    'temporal_name' => 'Temp Name'
];